export enum ActionTypes {
  SET_CHECKBOX_NAME_ALL = 'SET_CHECKBOX_NAME_ALL',
  SET_CHECKBOX_NAME_ALL_REVERSE = 'SET_CHECKBOX_NAME_ALL_REVERSE',
  SET_CHECKBOX_NAME_NO_TRANSFERS = 'SET_CHECKBOX_NAME_NO_TRANSFERS',
  SET_CHECKBOX_NAME_ONE_TRANSFER = 'SET_CHECKBOX_NAME_ONE_TRANSFER',
  SET_CHECKBOX_NAME_TWO_TRANSFERS = 'SET_CHECKBOX_NAME_TWO_TRANSFERS',
  SET_CHECKBOX_NAME_THREE_TRANFERS = 'SET_CHECKBOX_NAME_THREE_TRANFERS',
  SET_CHECKBOX_NAME_ALL_TO_TRUE = 'SET_CHECKBOX_NAME_ALL_TO_TRUE',
  SET_CHECKBOX_NAME_ALL_TO_FALSE = 'SET_CHECKBOX_NAME_ALL_TO_FALSE',
  COUNTER_FOOTER_BUTTON = 'COUNTER_FOOTER_BUTTON',
  SHOW_MORE_TICKETS_BUTTON = 'SHOW_MORE_TICKETS_BUTTON',
  HIDE_MORE_TICKETS_BUTTON = 'HIDE_MORE_TICKETS_BUTTON',
  SHOW_ALERT_MODAL = 'SHOW_ALERT_MODAL',
  HIDE_ALERT_MODAL = 'HIDE_ALERT_MODAL',
}

export enum fetchAtcionTypes {
  FETCH_TICKETS = 'FETCH_TICKETS',
  FETCH_TICKETS_SEARCH_ID = 'FETCH_TICKETS_SEARCH_ID',
  FETCH_TICKETS_SUCCSESS = 'FETCH_TICKETS_SUCCSESS',
  FETCH_TICKETS_ERROR = 'FETCH_TICKETS_ERROR',
}


