export enum ActionTypes {
  SET_ALL_CHECKBOX_TRUE = 'SET_ALL_CHECKBOX_TRUE',
  SET_ALL_CHECKBOX_FALSE = 'SET_ALL_CHECKBOX_FALSE',
  SET_CHECKBBOX_NO_TRANSFERS = 'SET_CHECKBBOX_NO_TRANSFERS',
  SET_CHECKBOX_ONE_TRANSFER = 'SET_CHECKBOX_ONE_TRANSFER',
  SET_CHECKBOX_TWO_TRANSFERS = 'SET_CHECKBOX_TWO_TRANSFERS',
  SET_CHECKBOX_THREE_TRANSFERS = 'SET_CHECKBOX_THREE_TRANSFERS',
}
