export enum ActionTypes {
  SET_CHECKBOX_NAME_ALL = 'SET_CHECKBOX_NAME_ALL',
  SET_CHECKBOX_NAME_ALL_REVERSE = 'SET_CHECKBOX_NAME_ALL_REVERSE',
  SET_CHECKBOX_NAME_NO_TRANSFERS = 'SET_CHECKBOX_NAME_NO_TRANSFERS',
  SET_CHECKBOX_NAME_ONE_TRANSFER = 'SET_CHECKBOX_NAME_ONE_TRANSFER',
  SET_CHECKBOX_NAME_TWO_TRANSFERS = 'SET_CHECKBOX_NAME_TWO_TRANSFERS',
  SET_CHECKBOX_NAME_THREE_TRANFERS = 'SET_CHECKBOX_NAME_THREE_TRANFERS',
  SET_CHECKBOX_NAME_ALL_TO_TRUE = 'SET_CHECKBOX_NAME_ALL_TO_TRUE',
  SET_CHECKBOX_NAME_ALL_TO_FALSE = 'SET_CHECKBOX_NAME_ALL_TO_FALSE',
}
